spring.application.name=bank-transaction-api
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.datasource.url=${NEON_JDBC_URL:jdbc:postgresql://ep-spring-hall-anwcfft4-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require&connectTimeout=10&socketTimeout=30}
spring.datasource.username=${NEON_DB_USERNAME:neondb_owner}
spring.datasource.password=${NEON_DB_PASSWORD:npg_pTKCry4Oaf2F}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.connection-timeout=30000
