spring.application.name=bank-transaction-api
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.datasource.url=${NEON_JDBC_URL:jdbc:postgresql://ep-spring-hall-anwcfft4-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require&connectTimeout=10&socketTimeout=30}
spring.datasource.username=${NEON_DB_USERNAME:neondb_owner}
spring.datasource.password=${NEON_DB_PASSWORD:npg_pTKCry4Oaf2F}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.connection-timeout=30000

# ===============================================
# =       Configuration pour l'envoi d'e-mails (Gmail)
# ===============================================
# ATTENTION : Pour des raisons de sécurité, il est fortement recommandé de ne pas stocker
# le mot de passe en clair dans ce fichier. Utilisez des variables d'environnement
# ou un service de gestion des secrets pour les environnements de production.
# Pour que cela fonctionne, vous devez générer un "mot de passe d'application"
# depuis votre compte Google et l'utiliser ici.
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=oberlinkeyanfe@gmail.com
spring.mail.password=oberlin1@@@
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

